### ISSUE TITLE
Add return to the top page button

### ISSUE THREAD

**Issue by punpongsanon** [SENSlab/senslab.github.io#1]
In the page, https://senslab.github.io/history.html, I think it is good to add the button to jump back to the top of the page.

**Comment by decarbonite** [comment]
When I scroll down in the link you provided, a button in the right bottom corner appears to return to the top of the page, isn't this what you are asking for?

**Comment by narugit** [comment]
@decarbonite 
Your answer is to the point. Thank you!!
