### ISSUE TITLE
Add leaflet

### ISSUE THREAD

**Issue by punpongsanon** [SENSlab/senslab.github.io#2]
Do we need to add the leaflet, somewhere in the first page ...
http://www.sens.sys.es.osaka-u.ac.jp/leaflet-2015a.pdf, **maybe as the link under 'ourlab'**

**Comment by narugit** [comment]
I think the leaflet is too old, so I will ask Sato-Sensei that we need to add in the homepage even if the leaflet is old.

**Comment by punpongsanon** [comment]
Sure thanks!

**Comment by narugit** [comment]
@punpongsanon 
Sato-Sensei said that he will make new leaflet, then send it to me.
After I get new leaflet, I will add it in the first page.

**Comment by narugit** [comment]
@punpongsanon 
I've added!
