### ISSUE TITLE
On going swap to sens.sys.es.osaka-u.ac.jp

### ISSUE THREAD

**Issue by punpongsanon** [SENSlab/senslab.github.io#20]
We are currently pointing this page to osaka-u.ac.jp DNS. Some features might not work during the swapping process.

**I will let you know the progress later.**
[O] send a request to sysadmin
[   ] admin reply and perform a swap
[   ] recovery DNS

**Comment by punpongsanon** [comment]
We just set a new DNS today (09/13) and wait for the DNS server to update. If this is not working, we will revise it with a new method tomorrow. Current setting is set as _APEX_ method not the _sub-domain_ method.

**change in 'A' file**
sens   3600  IN  A 185.199.108.153
sens   3600  IN  A 185.199.109.153
sens   3600  IN  A 185.199.110.153
sens   3600  IN  A 185.199.111.153
**change in CNAME**
www-sens IN CNAME sens
www.sens IN CNAME sens

point github pages to 'www-sens.sys.es.osaka-u.ac.jp'.

Thanks @narugit  for helping with this.

**Comment by narugit** [comment]
Also 
**change in MX 1**
sens IN MX 1 sens

**Comment by narugit** [comment]
@punpongsanon
I think we should not set like below.
`sens IN MX1 sens`
MX record set where mail server is.

So, I think we should set like below.
`sens IN MX1 senssyses.sakura.ne.jp.`

What do you think about this?

**Comment by narugit** [comment]
We change the zone file like below today (9/14 10:00 am).

**disable A record**
```
;sens IN A 185.199.108.153
;sens IN A 185.199.109.153
;sens IN A 185.199.110.153
;sens IN A 185.199.111.153
```

**change CNAME record**
```
www-sens IN CNAME senslab.github.io.
www.sens IN CNAME senslab.github.io.
```

**restore MX record**
```
sens IN MX 1 senssyses.sakura.ne.jp.
```

I am appreciate that @punpongsanon helped with this.

**Comment by narugit** [comment]
After we change zone file, we should reload it.
```
# rndc reload
```

**Comment by narugit** [comment]
@narugit and @kamino410 changed the zone file like below today (9/18 19:00).

**change CNAME record**
```
;www-sens IN CNAME senslab.github.io.
www.sens IN CNAME senslab.github.io.
```

**Comment by narugit** [comment]
# Summary
1. Set the custom domain for our github page. 
151cf36 handles it. 
We need to deploy with `npm run deploy`.

1. Set the cname in DNS.

    ```
    www.sens IN CNAME senslab.github.io.
    www-sens IN CNAME senslab.github.io.
    ```

    The reason we need to set both `www.sens` and `www-sens` is that other pages may refer either `www.sens` or `www-sens`.

1. Reload the zone file.
    
    ```
    # rndc reload
    ```

1. Wait for a while.

1. Go [Settings](https://github.com/SENSlab/senslab.github.io/settings) and check `Enforce HTTPS`.

**Comment by punpongsanon** [comment]
Thank you both @narugit and @kamino410. The job done. Sorry that I cannot help and figure it out.

**Comment by narugit** [comment]
I reopen this issue.
We should 
- add `SERIAL` value in SOA record. 
- unset CNAME record, `www-sens IN CNAME senslab.github.io.`
- set A record as 
    ```
    www-sens.   3600  IN  A 185.199.108.153
    www-sens.   3600  IN  A 185.199.109.153
    www-sens.   3600  IN  A 185.199.110.153
    www-sens.   3600  IN  A 185.199.111.153
    ```
    Actually, this A record setting is temporary. 
    After other pages does not refer `www-sens` page, we will unset A record.
    It's because if GitHub Pages server change their ip address, we need to change A record.
    This result in low serviceability.

**Comment by narugit** [comment]
Today, I added `SERIAL` value in SOA record.

**Comment by narugit** [comment]
Finally, the work is done.
