### ISSUE TITLE
Narrowing down is not cleared on exit with esc

### ISSUE THREAD

**Issue by kamino410** [SENSlab/senslab.github.io#22]
In the publication search, filter is not cleared when exit with escape key.

It is reproducible with not `ng serve` but production (github pages).

**Comment by narugit** [comment]
In my environment, the issue does not reproduced.

**My environment**
- Windows 10
- Google Chrome (69.0.3497.81) 64-bit

**Comment by kamino410** [comment]
I recommend to make clear button on the right side of search input.
