### ISSUE TITLE
Member photos request

### ISSUE THREAD

**Issue by narugit** [SENSlab/senslab.github.io#3]
If you want to add your member's photo, please comment and show the photo here. 
You can drag and drop the image.

Please set
- **aspect ratio to 1:1**
- **file extension to jpg**

メンバーページにて公開してもよいプロフィール写真がございましたら、こちらにコメント下さい。
写真はドラッグアンドドロップで添付できます。

- **アスペクト比は1:1**
- **拡張子はjpg**

でお願いします。

**Comment by mineryugit** [comment]
# 写真
![default](https://user-images.githubusercontent.com/28133671/43705560-d2414a30-999d-11e8-8fa6-b9d715e9139a.png)


# コメント
M2峯です。こちらの写真でお願いいたします。

**Comment by narugit** [comment]
@mineryugit 

早速の投稿、ありがとうございます。
アスペクト比を1:1にして頂いてもよろしいでしょうか。

**Comment by youseegreen** [comment]
![dg3gc6luqaeylot](https://user-images.githubusercontent.com/39123031/43697198-679196d8-997d-11e8-988d-e44129e6845d.jpg)

B4佐藤です。この写真でお願いいたします。

**Comment by Takasens** [comment]
### 写真
![img_9985](https://user-images.githubusercontent.com/30895457/43701363-e883ddc4-9990-11e8-8006-780c7dd1629a.jpg)

### コメント
M2佐藤です。この写真でお願いします。

**Comment by mineryugit** [comment]
@narugit 
アスペクト比修正いたしました。
確認の程、よろしくお願いいたします。

**Comment by koromochu9999** [comment]
![img_20180807_133127 1](https://user-images.githubusercontent.com/39985906/43758008-b6e081a8-9a55-11e8-8f31-a044b3b51ce3.jpg)


藤野ですよろしくお願いします

**Comment by Kosusuke** [comment]
![dsc_0413](https://user-images.githubusercontent.com/40199662/44447317-92fdb700-a622-11e8-9533-8a064de12613.JPG)
