### ISSUE TITLE
Fix font / icon size

### ISSUE THREAD

**Issue by kamino410** [SENSlab/senslab.github.io#4]
The following is a list of apparent bug I found.

* [x] Top -> Our Lab -> `History of SENS / 佐藤研究室の沿革`
  * Icon becomes too large (width:~760px).
  * Font is too large when hover on it (width:770px~).
* [x] Classes -> `[2010, 2011, ~~~~~~~]`
  * Font size changes depending on linked/unlinked.
* [x] Footer -> Icons of `Anniversary 2021` and `Osaka University Log`
  * Icons are overwrapped (width:760px~).
  * They are aligned vertically (width:~760px).

**Comment by narugit** [comment]
@kamino410 
Thanks!
I fixed that the font size chenges depending on linked/unlinked.

**Comment by narugit** [comment]
I fixed the icons' style in footer.

**Comment by narugit** [comment]
I fixed icon and font size in history page.
