### ISSUE TITLE
Migrate to SPA

### ISSUE THREAD

**Issue by kamino410** [SENSlab/senslab.github.io#5]
The current our web page reloads all elements at every page translations.
But header, footer and bootstrap css are used in common.

So I recommend to migrate to SPA (Single Page Application) which reloads minimal resources when needed.

Recently, there are some lightweight frameworks to develop static SPA.
* [React Static](https://github.com/nozzle/react-static/)
* [Next.js](https://github.com/zeit/next.js/)
* [Nuxt.js](https://github.com/nuxt/nuxt.js/)

It seems to be not so difficult...

**Comment by narugit** [comment]
@kamino410 
Thank you for great recommendation!
I'll check it.

**Comment by punpongsanon** [comment]
How the elements really load the traffic? 

Consider traffic we have (recently) compare to what we have to do more work, I don't think this is the high priority, right now. However, it is good to enhance for the next version. 

PS. you should consider contributing :) our lab website as you know more than what we know. Let me know, and joint the team...

**Comment by punpongsanon** [comment]
Check it! look easy but, I feel it requires some effort for maintenance (let me know if I wrong ...)

**Comment by kamino410** [comment]
Yes, this should be low priority issue.
And I guess the traffic load is not big deal.
However, visual effects are improved with SPA because it doesn't blink at page transition and the header menu will be closed smoothly.

I'm worried about the updating trouble too.
It would be good to make a simple demo and check the maintenance cost when we have time.

**Comment by punpongsanon** [comment]
Totally agree.
